language: python
sudo: false

deploy:
  provider: pypi
  user: brucebcampbell
  password:
    secure: $PYPI_PASSWORD
  on:
    tags: true
    repo: brucebcampbell/nlp_modelling


python:
  - '3.6'

install:
- travis_retry pip install sphinx
- travis_retry pip install sphinx_gallery
- travis_retry pip install sphinx_rtd_theme
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
#- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- mkdir for_test
- cd for_test
- py.test --pyargs pytma --cov-report term-missing --cov=pytma
#- sphinx-build -nWT -b dummy . _build/html
- cd /home/travis/build/brucebcampbell/nlp-modelling/doc
- make html


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: "doc/_build/html"
  keep_history: true
  on:
    branch: master


after_success:
- coveralls
